language: android
android:
  components:
    - tools
    - build-tools-23.0.1
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

licenses:
 - 'android-sdk-license-.+'

before_install:
 - chmod +x gradlew