language: android
jdk: oraclejdk8
env:
  global:
   - ANDROID_API_LEVEL=21
   - EMULATOR_API_LEVEL=21
   - ANDROID_BUILD_TOOLS_VERSION=23.0.1
   - ANDROID_ABI=google_apis/armeabi-v7a
   - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$EMULATOR_API_LEVEL
    - extra-google-google_play_services
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

before_install:
 - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
 - ./gradlew clean
 - ./gradlew connectedCheck -PdisablePreDex
 - ./gradlew build check
 - ./gradlew build jacocoTestReport


after_success:
 - ./gradlew uploadArchives
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false