language: android
jdk: oraclejdk7
env:
  global:
   - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - extra
    - sys-img-armeabi-v7a-android-21
    - addon-google_apis-google-23
    - addon-google_apis-google-21

before_install:
 - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"21 --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
 - ./gradlew connectedCheck -x library:signArchives -PdisablePreDex
 - ./gradlew build check
 - ./gradlew build jacocoTestReport


after_success:
 - ./gradlew uploadArchives
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false