language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
    - extra
    - sys-img-armeabi-v7a-android-23

before_install:
 - chmod +x gradlew

script:
 - ./gradlew build check
 - ./gradlew build jacocoTestReport


after_success:
 - ./gradlew uploadArchives
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false